name: home-assistant

services:
  home-assistant:
    container_name: home-assistant
    privileged: true
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./config:/config
      - /media/Ziegel/Bilder:/media/Bilder:ro  
      - /media/Ziegel/Videos:/media/Videos:ro  
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro  
    network_mode: host
    image: "ghcr.io/home-assistant/home-assistant:${HOME_ASSISTANT_VERSION}"
    labels:
      - traefik.enable=true
      - traefik.http.services.home-assistant.loadbalancer.server.port=8123
      - traefik.http.routers.home-assistant.rule=Host(`home.elisman.de`)
      - traefik.http.routers.home-assistant.entrypoints=websecure      
      - traefik.http.routers.home-assistant.tls=true
      - traefik.http.routers.home-assistant.tls.certresolver=lets-encrypt
